// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Studica.Students.Client
{
    using Models;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for ActiveStudentsExternal.
    /// </summary>
    public static partial class ActiveStudentsExternalExtensions
    {
            /// <summary>
            /// ActiveStudentsExternal_Get
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='pageNumber'>
            /// Format - int32. The number of the page to return (1 is the first page).
            /// </param>
            /// <param name='pageSize'>
            /// Format - int32. Number of objects per page.
            /// </param>
            /// <param name='inlineCount'>
            /// A flag indicating if total number of items should be included.
            /// </param>
            /// <param name='schoolCode'>
            /// The school code for which to get data.
            /// </param>
            /// <param name='studentActiveOnOrAfterDate'>
            /// Format - date (as full-date in RFC3339). Students must be active on the
            /// date or after this date
            /// This parameter is required
            /// </param>
            public static PagedResponseStudentExternalResponse Get(this IActiveStudentsExternal operations, int pageNumber, int pageSize, bool inlineCount, string schoolCode, System.DateTime? studentActiveOnOrAfterDate = default(System.DateTime?))
            {
                return operations.GetAsync(pageNumber, pageSize, inlineCount, schoolCode, studentActiveOnOrAfterDate).GetAwaiter().GetResult();
            }

            /// <summary>
            /// ActiveStudentsExternal_Get
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='pageNumber'>
            /// Format - int32. The number of the page to return (1 is the first page).
            /// </param>
            /// <param name='pageSize'>
            /// Format - int32. Number of objects per page.
            /// </param>
            /// <param name='inlineCount'>
            /// A flag indicating if total number of items should be included.
            /// </param>
            /// <param name='schoolCode'>
            /// The school code for which to get data.
            /// </param>
            /// <param name='studentActiveOnOrAfterDate'>
            /// Format - date (as full-date in RFC3339). Students must be active on the
            /// date or after this date
            /// This parameter is required
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<PagedResponseStudentExternalResponse> GetAsync(this IActiveStudentsExternal operations, int pageNumber, int pageSize, bool inlineCount, string schoolCode, System.DateTime? studentActiveOnOrAfterDate = default(System.DateTime?), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetWithHttpMessagesAsync(pageNumber, pageSize, inlineCount, schoolCode, studentActiveOnOrAfterDate, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
