// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Studica.Employees.Client
{
    using Models;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for Employees.
    /// </summary>
    public static partial class EmployeesExtensions
    {
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='pageNumber'>
            /// </param>
            /// <param name='pageSize'>
            /// </param>
            /// <param name='inlineCount'>
            /// </param>
            /// <param name='employmentStartDateFrom'>
            /// </param>
            /// <param name='employmentStartDateTo'>
            /// </param>
            /// <param name='institutionNumber'>
            /// Institution number the employee belongs to.
            /// </param>
            public static PagedResponse1 Get(this IEmployees operations, int pageNumber, int pageSize, bool inlineCount, System.DateTime employmentStartDateFrom, System.DateTime employmentStartDateTo, string institutionNumber = default(string))
            {
                return operations.GetAsync(pageNumber, pageSize, inlineCount, employmentStartDateFrom, employmentStartDateTo, institutionNumber).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='pageNumber'>
            /// </param>
            /// <param name='pageSize'>
            /// </param>
            /// <param name='inlineCount'>
            /// </param>
            /// <param name='employmentStartDateFrom'>
            /// </param>
            /// <param name='employmentStartDateTo'>
            /// </param>
            /// <param name='institutionNumber'>
            /// Institution number the employee belongs to.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<PagedResponse1> GetAsync(this IEmployees operations, int pageNumber, int pageSize, bool inlineCount, System.DateTime employmentStartDateFrom, System.DateTime employmentStartDateTo, string institutionNumber = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetWithHttpMessagesAsync(pageNumber, pageSize, inlineCount, employmentStartDateFrom, employmentStartDateTo, institutionNumber, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
