// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Studica.Statistics.Client
{
    using Models;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for SubmitHandinsExternal.
    /// </summary>
    public static partial class SubmitHandinsExternalExtensions
    {
            /// <summary>
            /// SubmitHandinsExternal_Post
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='handins'>
            /// New handins to create
            /// </param>
            /// <param name='schoolCode'>
            /// String The school code for which to get data.
            /// </param>
            public static void Post(this ISubmitHandinsExternal operations, IList<ExternalHandinDto> handins, string schoolCode)
            {
                operations.PostAsync(handins, schoolCode).GetAwaiter().GetResult();
            }

            /// <summary>
            /// SubmitHandinsExternal_Post
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='handins'>
            /// New handins to create
            /// </param>
            /// <param name='schoolCode'>
            /// String The school code for which to get data.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task PostAsync(this ISubmitHandinsExternal operations, IList<ExternalHandinDto> handins, string schoolCode, CancellationToken cancellationToken = default(CancellationToken))
            {
                (await operations.PostWithHttpMessagesAsync(handins, schoolCode, null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

    }
}
