// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Studica.Programmes.Client
{
    using Models;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for AbsenceRegistrationsExternal.
    /// </summary>
    public static partial class AbsenceRegistrationsExternalExtensions
    {
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='schoolCode'>
            /// The school code for which to get data.
            /// </param>
            /// <param name='pageNumber'>
            /// The page number to return.
            /// </param>
            /// <param name='pageSize'>
            /// Number of objects per page.
            /// </param>
            /// <param name='inlineCount'>
            /// A flag indicating if include total number of items.
            /// </param>
            /// <param name='dateFrom'>
            /// Beginning of the range for absence date. The `DateFrom` parameter
            /// determines date to get absence data from, as well as the school year period
            /// </param>
            /// <param name='dateTo'>
            /// End of the range for absence date.
            /// The `DateTo` parameter must be within the same school year as `DateFrom`
            /// </param>
            /// <param name='studentId'>
            /// Absent student.
            /// </param>
            /// <param name='lessonId'>
            /// Lesson of absence.
            /// </param>
            /// <param name='onlyAbsenceReports'>
            /// Only retrieve reports of absence or partial absence,
            /// defaults to false (retrieve everything)
            /// </param>
            public static PagedResponseAbsenceRegistrationExternalResponse Get(this IAbsenceRegistrationsExternal operations, string schoolCode, int pageNumber, int pageSize, bool inlineCount, System.DateTime dateFrom, System.DateTime dateTo, System.Guid? studentId = default(System.Guid?), System.Guid? lessonId = default(System.Guid?), bool? onlyAbsenceReports = default(bool?))
            {
                return operations.GetAsync(schoolCode, pageNumber, pageSize, inlineCount, dateFrom, dateTo, studentId, lessonId, onlyAbsenceReports).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='schoolCode'>
            /// The school code for which to get data.
            /// </param>
            /// <param name='pageNumber'>
            /// The page number to return.
            /// </param>
            /// <param name='pageSize'>
            /// Number of objects per page.
            /// </param>
            /// <param name='inlineCount'>
            /// A flag indicating if include total number of items.
            /// </param>
            /// <param name='dateFrom'>
            /// Beginning of the range for absence date. The `DateFrom` parameter
            /// determines date to get absence data from, as well as the school year period
            /// </param>
            /// <param name='dateTo'>
            /// End of the range for absence date.
            /// The `DateTo` parameter must be within the same school year as `DateFrom`
            /// </param>
            /// <param name='studentId'>
            /// Absent student.
            /// </param>
            /// <param name='lessonId'>
            /// Lesson of absence.
            /// </param>
            /// <param name='onlyAbsenceReports'>
            /// Only retrieve reports of absence or partial absence,
            /// defaults to false (retrieve everything)
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<PagedResponseAbsenceRegistrationExternalResponse> GetAsync(this IAbsenceRegistrationsExternal operations, string schoolCode, int pageNumber, int pageSize, bool inlineCount, System.DateTime dateFrom, System.DateTime dateTo, System.Guid? studentId = default(System.Guid?), System.Guid? lessonId = default(System.Guid?), bool? onlyAbsenceReports = default(bool?), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetWithHttpMessagesAsync(schoolCode, pageNumber, pageSize, inlineCount, dateFrom, dateTo, studentId, lessonId, onlyAbsenceReports, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
