// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Studica.Programmes.Client.Models
{
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// AbsenceRegistrationExternalResponse
    /// </summary>
    /// <remarks>
    /// The model of absence.
    /// </remarks>
    public partial class AbsenceRegistrationExternalResponse
    {
        /// <summary>
        /// Initializes a new instance of the
        /// AbsenceRegistrationExternalResponse class.
        /// </summary>
        public AbsenceRegistrationExternalResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// AbsenceRegistrationExternalResponse class.
        /// </summary>
        /// <param name="studentId">Guid</param>
        /// <param name="lessonId">Guid</param>
        /// <param name="absenceDate">Date</param>
        /// <param name="minutes">Int32</param>
        /// <param name="approved">Boolean</param>
        /// <param name="status">AbsenceRegistrationStatus</param>
        public AbsenceRegistrationExternalResponse(System.Guid studentId, System.Guid lessonId, System.DateTime absenceDate, int minutes, bool approved, string status)
        {
            StudentId = studentId;
            LessonId = lessonId;
            AbsenceDate = absenceDate;
            Minutes = minutes;
            Approved = approved;
            Status = status;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets guid
        /// </summary>
        /// <remarks>
        /// Absent student id.
        /// </remarks>
        [JsonProperty(PropertyName = "studentId")]
        public System.Guid StudentId { get; set; }

        /// <summary>
        /// Gets or sets guid
        /// </summary>
        /// <remarks>
        /// Lesson (or session) id.
        /// </remarks>
        [JsonProperty(PropertyName = "lessonId")]
        public System.Guid LessonId { get; set; }

        /// <summary>
        /// Gets or sets date
        /// </summary>
        /// <remarks>
        /// Date of absence.
        /// </remarks>
        [JsonConverter(typeof(DateJsonConverter))]
        [JsonProperty(PropertyName = "absenceDate")]
        public System.DateTime AbsenceDate { get; set; }

        /// <summary>
        /// Gets or sets int32
        /// </summary>
        /// <remarks>
        /// The length of the absence in minutes.
        /// </remarks>
        [JsonProperty(PropertyName = "minutes")]
        public int Minutes { get; set; }

        /// <summary>
        /// Gets or sets boolean
        /// </summary>
        /// <remarks>
        /// Was absence approved.
        /// </remarks>
        [JsonProperty(PropertyName = "approved")]
        public bool Approved { get; set; }

        /// <summary>
        /// Gets or sets absenceRegistrationStatus
        /// </summary>
        /// <remarks>
        /// Type of absence. Possible values include: 'Present', 'Absent',
        /// 'PartialAbsence', 'NotRegistered'
        /// </remarks>
        [JsonProperty(PropertyName = "status")]
        public string Status { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Status == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Status");
            }
        }
    }
}
