// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Studica.Programmes.Client.Models
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// The original report.
    /// </summary>
    public partial class ActivityGroupDtoOriginalReport : ActivityReportDto
    {
        /// <summary>
        /// Initializes a new instance of the ActivityGroupDtoOriginalReport
        /// class.
        /// </summary>
        public ActivityGroupDtoOriginalReport()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ActivityGroupDtoOriginalReport
        /// class.
        /// </summary>
        /// <param name="sequenceNumber">Int32</param>
        /// <param name="lastEdited">The last time the report was
        /// edited</param>
        /// <param name="reportedOn">The time at which the Report was
        /// reported</param>
        /// <param name="status">String</param>
        /// <param name="activityReportsRows">List of data rows in the
        /// report</param>
        public ActivityGroupDtoOriginalReport(int sequenceNumber, System.DateTime? lastEdited = default(System.DateTime?), System.DateTime? reportedOn = default(System.DateTime?), string status = default(string), IList<ActivityReportRowDto> activityReportsRows = default(IList<ActivityReportRowDto>))
            : base(sequenceNumber, lastEdited, reportedOn, status, activityReportsRows)
        {
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public override void Validate()
        {
            base.Validate();
        }
    }
}
