// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Studica.Programmes.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// ActivityReportRowDto
    /// </summary>
    public partial class ActivityReportRowDto
    {
        /// <summary>
        /// Initializes a new instance of the ActivityReportRowDto class.
        /// </summary>
        public ActivityReportRowDto()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ActivityReportRowDto class.
        /// </summary>
        /// <param name="institutionNumber">String</param>
        /// <param name="requestor">String</param>
        /// <param name="coesaVersion">String</param>
        /// <param name="education">String</param>
        /// <param name="specialisation">String</param>
        /// <param name="entryRoute">String</param>
        /// <param name="studentType">String</param>
        /// <param name="subject">String</param>
        /// <param name="tmk">String</param>
        /// <param name="tmkType">String</param>
        /// <param name="schoolPeriod">String</param>
        public ActivityReportRowDto(System.Guid id, string institutionNumber = default(string), string requestor = default(string), string coesaVersion = default(string), string education = default(string), string specialisation = default(string), string entryRoute = default(string), string studentType = default(string), string subject = default(string), string tmk = default(string), string tmkType = default(string), string schoolPeriod = default(string), int? countingPeriod = default(int?), double? numberOfGrantDays = default(double?), IList<ActivityReportsStudentActivityDto> studentActivity = default(IList<ActivityReportsStudentActivityDto>))
        {
            Id = id;
            InstitutionNumber = institutionNumber;
            Requestor = requestor;
            CoesaVersion = coesaVersion;
            Education = education;
            Specialisation = specialisation;
            EntryRoute = entryRoute;
            StudentType = studentType;
            Subject = subject;
            Tmk = tmk;
            TmkType = tmkType;
            SchoolPeriod = schoolPeriod;
            CountingPeriod = countingPeriod;
            NumberOfGrantDays = numberOfGrantDays;
            StudentActivity = studentActivity;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public System.Guid Id { get; set; }

        /// <summary>
        /// Gets or sets string
        /// </summary>
        [JsonProperty(PropertyName = "institutionNumber")]
        public string InstitutionNumber { get; set; }

        /// <summary>
        /// Gets or sets string
        /// </summary>
        [JsonProperty(PropertyName = "requestor")]
        public string Requestor { get; set; }

        /// <summary>
        /// Gets or sets string
        /// </summary>
        [JsonProperty(PropertyName = "coesaVersion")]
        public string CoesaVersion { get; set; }

        /// <summary>
        /// Gets or sets string
        /// </summary>
        [JsonProperty(PropertyName = "education")]
        public string Education { get; set; }

        /// <summary>
        /// Gets or sets string
        /// </summary>
        [JsonProperty(PropertyName = "specialisation")]
        public string Specialisation { get; set; }

        /// <summary>
        /// Gets or sets string
        /// </summary>
        [JsonProperty(PropertyName = "entryRoute")]
        public string EntryRoute { get; set; }

        /// <summary>
        /// Gets or sets string
        /// </summary>
        [JsonProperty(PropertyName = "studentType")]
        public string StudentType { get; set; }

        /// <summary>
        /// Gets or sets string
        /// </summary>
        [JsonProperty(PropertyName = "subject")]
        public string Subject { get; set; }

        /// <summary>
        /// Gets or sets string
        /// </summary>
        [JsonProperty(PropertyName = "tmk")]
        public string Tmk { get; set; }

        /// <summary>
        /// Gets or sets string
        /// </summary>
        [JsonProperty(PropertyName = "tmkType")]
        public string TmkType { get; set; }

        /// <summary>
        /// Gets or sets string
        /// </summary>
        [JsonProperty(PropertyName = "schoolPeriod")]
        public string SchoolPeriod { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "countingPeriod")]
        public int? CountingPeriod { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "numberOfGrantDays")]
        public double? NumberOfGrantDays { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "studentActivity")]
        public IList<ActivityReportsStudentActivityDto> StudentActivity { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (StudentActivity != null)
            {
                foreach (var element in StudentActivity)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
