// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Studica.Programmes.Client.Models
{
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// BulkAbsenceRegistrationsExternalRequest
    /// </summary>
    /// <remarks>
    /// Returns a paged list of absences satisfying provided criteria.
    /// </remarks>
    public partial class BulkAbsenceRegistrationsExternalRequest
    {
        /// <summary>
        /// Initializes a new instance of the
        /// BulkAbsenceRegistrationsExternalRequest class.
        /// </summary>
        public BulkAbsenceRegistrationsExternalRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// BulkAbsenceRegistrationsExternalRequest class.
        /// </summary>
        /// <param name="studentIds">A list of student ids to get absence
        /// for.</param>
        /// <param name="dateFrom">Date</param>
        /// <param name="dateTo">Date</param>
        /// <param name="schoolCode">String</param>
        public BulkAbsenceRegistrationsExternalRequest(IList<System.Guid> studentIds, System.DateTime dateFrom, System.DateTime dateTo, string schoolCode)
        {
            StudentIds = studentIds;
            DateFrom = dateFrom;
            DateTo = dateTo;
            SchoolCode = schoolCode;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets a list of student ids to get absence for.
        /// </summary>
        [JsonProperty(PropertyName = "studentIds")]
        public IList<System.Guid> StudentIds { get; set; }

        /// <summary>
        /// Gets or sets date
        /// </summary>
        /// <remarks>
        /// Beginning of the range for absence date.
        /// </remarks>
        [JsonConverter(typeof(DateJsonConverter))]
        [JsonProperty(PropertyName = "dateFrom")]
        public System.DateTime DateFrom { get; set; }

        /// <summary>
        /// Gets or sets date
        /// </summary>
        /// <remarks>
        /// End of the range for absence date.
        /// </remarks>
        [JsonConverter(typeof(DateJsonConverter))]
        [JsonProperty(PropertyName = "dateTo")]
        public System.DateTime DateTo { get; set; }

        /// <summary>
        /// Gets or sets string
        /// </summary>
        /// <remarks>
        /// The school code for which to get data.
        /// </remarks>
        [JsonProperty(PropertyName = "schoolCode")]
        public string SchoolCode { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (StudentIds == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "StudentIds");
            }
            if (SchoolCode == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "SchoolCode");
            }
            if (SchoolCode != null)
            {
                if (SchoolCode.Length > 6)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "SchoolCode", 6);
                }
                if (SchoolCode.Length < 6)
                {
                    throw new ValidationException(ValidationRules.MinLength, "SchoolCode", 6);
                }
            }
        }
    }
}
