// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Studica.Programmes.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// LevelDetails
    /// </summary>
    public partial class LevelDetails
    {
        /// <summary>
        /// Initializes a new instance of the LevelDetails class.
        /// </summary>
        public LevelDetails()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the LevelDetails class.
        /// </summary>
        public LevelDetails(System.Guid levelId, string level = default(string), string description = default(string), string levelType = default(string))
        {
            LevelId = levelId;
            Level = level;
            Description = description;
            LevelType = levelType;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "levelId")]
        public System.Guid LevelId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "level")]
        public string Level { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "levelType")]
        public string LevelType { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
