// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Studica.Programmes.Client.Models
{
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// StudentInternship_WrittenAgreement
    /// </summary>
    /// <remarks>
    /// A student's written agreement for school based internship
    /// </remarks>
    public partial class StudentInternshipWrittenAgreement
    {
        /// <summary>
        /// Initializes a new instance of the StudentInternshipWrittenAgreement
        /// class.
        /// </summary>
        public StudentInternshipWrittenAgreement()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the StudentInternshipWrittenAgreement
        /// class.
        /// </summary>
        /// <param name="startDate">Date</param>
        /// <param name="endDate">Date</param>
        /// <param name="agreementType">String</param>
        /// <param name="agreementTypeDescription">String</param>
        public StudentInternshipWrittenAgreement(System.DateTime startDate, System.DateTime endDate, string agreementType = default(string), string agreementTypeDescription = default(string))
        {
            AgreementType = agreementType;
            AgreementTypeDescription = agreementTypeDescription;
            StartDate = startDate;
            EndDate = endDate;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets string
        /// </summary>
        /// <remarks>
        /// The written agreement's internship type
        /// </remarks>
        [JsonProperty(PropertyName = "agreementType")]
        public string AgreementType { get; set; }

        /// <summary>
        /// Gets or sets string
        /// </summary>
        /// <remarks>
        /// Textual description of the internship type
        /// </remarks>
        [JsonProperty(PropertyName = "agreementTypeDescription")]
        public string AgreementTypeDescription { get; set; }

        /// <summary>
        /// Gets or sets date
        /// </summary>
        /// <remarks>
        /// Start date of internship
        /// </remarks>
        [JsonConverter(typeof(DateJsonConverter))]
        [JsonProperty(PropertyName = "startDate")]
        public System.DateTime StartDate { get; set; }

        /// <summary>
        /// Gets or sets date
        /// </summary>
        /// <remarks>
        /// End date for internship
        /// </remarks>
        [JsonConverter(typeof(DateJsonConverter))]
        [JsonProperty(PropertyName = "endDate")]
        public System.DateTime EndDate { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
