// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Studica.SchoolInternships.Client.Models
{
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// StudentsInternshipAbsence_AbsenceDto
    /// </summary>
    public partial class StudentsInternshipAbsenceAbsenceDto
    {
        /// <summary>
        /// Initializes a new instance of the
        /// StudentsInternshipAbsenceAbsenceDto class.
        /// </summary>
        public StudentsInternshipAbsenceAbsenceDto()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// StudentsInternshipAbsenceAbsenceDto class.
        /// </summary>
        /// <param name="date">Date</param>
        /// <param name="durationInMinutes">Int32</param>
        /// <param name="isFullDayAbsence">Boolean</param>
        /// <param name="absenceType">AbsenceType</param>
        public StudentsInternshipAbsenceAbsenceDto(System.DateTime date, int durationInMinutes, bool isFullDayAbsence, string absenceType)
        {
            Date = date;
            DurationInMinutes = durationInMinutes;
            IsFullDayAbsence = isFullDayAbsence;
            AbsenceType = absenceType;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets date
        /// </summary>
        [JsonConverter(typeof(DateJsonConverter))]
        [JsonProperty(PropertyName = "date")]
        public System.DateTime Date { get; set; }

        /// <summary>
        /// Gets or sets int32
        /// </summary>
        [JsonProperty(PropertyName = "durationInMinutes")]
        public int DurationInMinutes { get; set; }

        /// <summary>
        /// Gets or sets boolean
        /// </summary>
        [JsonProperty(PropertyName = "isFullDayAbsence")]
        public bool IsFullDayAbsence { get; set; }

        /// <summary>
        /// Gets or sets absenceType
        /// </summary>
        /// <remarks>
        /// Possible values include: 'Illness', 'IllegalAbsence',
        /// 'LegalAbsence', 'PaidVacation', 'UnpaidVacation'
        /// </remarks>
        [JsonProperty(PropertyName = "absenceType")]
        public string AbsenceType { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (AbsenceType == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "AbsenceType");
            }
        }
    }
}
