// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Studica.SchoolInternships.Client.Models
{
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// StudentInternshipsExternalRequest
    /// </summary>
    /// <remarks>
    /// Get a list of students having school internships within the specified
    /// period
    /// </remarks>
    public partial class StudentInternshipsExternalRequest
    {
        /// <summary>
        /// Initializes a new instance of the StudentInternshipsExternalRequest
        /// class.
        /// </summary>
        public StudentInternshipsExternalRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the StudentInternshipsExternalRequest
        /// class.
        /// </summary>
        /// <param name="periodFrom">Date</param>
        /// <param name="periodTo">Date</param>
        /// <param name="schoolCode">String</param>
        public StudentInternshipsExternalRequest(System.DateTime periodFrom, System.DateTime periodTo, string schoolCode)
        {
            PeriodFrom = periodFrom;
            PeriodTo = periodTo;
            SchoolCode = schoolCode;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets date
        /// </summary>
        /// <remarks>
        /// Get all students school internships starting on or after this date
        /// </remarks>
        [JsonConverter(typeof(DateJsonConverter))]
        [JsonProperty(PropertyName = "periodFrom")]
        public System.DateTime PeriodFrom { get; set; }

        /// <summary>
        /// Gets or sets date
        /// </summary>
        /// <remarks>
        /// Get all students school internships ending on or before this date
        /// </remarks>
        [JsonConverter(typeof(DateJsonConverter))]
        [JsonProperty(PropertyName = "periodTo")]
        public System.DateTime PeriodTo { get; set; }

        /// <summary>
        /// Gets or sets string
        /// </summary>
        /// <remarks>
        /// The school code for which to get data.
        /// </remarks>
        [JsonProperty(PropertyName = "schoolCode")]
        public string SchoolCode { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (SchoolCode == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "SchoolCode");
            }
            if (SchoolCode != null)
            {
                if (SchoolCode.Length > 6)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "SchoolCode", 6);
                }
                if (SchoolCode.Length < 6)
                {
                    throw new ValidationException(ValidationRules.MinLength, "SchoolCode", 6);
                }
            }
        }
    }
}
