// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Studica.SchoolInternships.Client
{
    using Models;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for StudentInternshipsExternalV2.
    /// </summary>
    public static partial class StudentInternshipsExternalV2Extensions
    {
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='periodFrom'>
            /// Get all students school internships starting on or after this date
            /// </param>
            /// <param name='periodTo'>
            /// Get all students school internships ending on or before this date
            /// </param>
            /// <param name='schoolCode'>
            /// The school code for which to get data.
            /// </param>
            public static IList<StudentInternshipsExternalV2Response> Get(this IStudentInternshipsExternalV2 operations, System.DateTime periodFrom, System.DateTime periodTo, string schoolCode)
            {
                return operations.GetAsync(periodFrom, periodTo, schoolCode).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='periodFrom'>
            /// Get all students school internships starting on or after this date
            /// </param>
            /// <param name='periodTo'>
            /// Get all students school internships ending on or before this date
            /// </param>
            /// <param name='schoolCode'>
            /// The school code for which to get data.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<StudentInternshipsExternalV2Response>> GetAsync(this IStudentInternshipsExternalV2 operations, System.DateTime periodFrom, System.DateTime periodTo, string schoolCode, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetWithHttpMessagesAsync(periodFrom, periodTo, schoolCode, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
