// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Studica.SchoolAdministration.Client
{
    using Microsoft.Rest;
    using Models;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// </summary>
    public partial interface IKMDStudicaSchoolAdministration : System.IDisposable
    {
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        System.Uri BaseUri { get; set; }

        /// <summary>
        /// Gets or sets json serialization settings.
        /// </summary>
        JsonSerializerSettings SerializationSettings { get; }

        /// <summary>
        /// Gets or sets json deserialization settings.
        /// </summary>
        JsonSerializerSettings DeserializationSettings { get; }

        /// <summary>
        /// Subscription credentials which uniquely identify client
        /// subscription.
        /// </summary>
        ServiceClientCredentials Credentials { get; }


        /// <summary>
        /// Gets the IActiveDepartmentsExternal.
        /// </summary>
        IActiveDepartmentsExternal ActiveDepartmentsExternal { get; }

        /// <summary>
        /// Gets the IAreasOfResponsibilityExternal.
        /// </summary>
        IAreasOfResponsibilityExternal AreasOfResponsibilityExternal { get; }

        /// <summary>
        /// Gets the IBulkAreasOfResponsibilityExternal.
        /// </summary>
        IBulkAreasOfResponsibilityExternal BulkAreasOfResponsibilityExternal { get; }

        /// <summary>
        /// Gets the IBulkDepartmentsExternal.
        /// </summary>
        IBulkDepartmentsExternal BulkDepartmentsExternal { get; }

        /// <summary>
        /// Gets the IBulkEmployeesExternal.
        /// </summary>
        IBulkEmployeesExternal BulkEmployeesExternal { get; }

        /// <summary>
        /// Gets the IBulkRoomsExternal.
        /// </summary>
        IBulkRoomsExternal BulkRoomsExternal { get; }

        /// <summary>
        /// Gets the IDayCalendarsExternal.
        /// </summary>
        IDayCalendarsExternal DayCalendarsExternal { get; }

        /// <summary>
        /// Gets the IDepartmentsExternal.
        /// </summary>
        IDepartmentsExternal DepartmentsExternal { get; }

        /// <summary>
        /// Gets the IEmployeesExternal.
        /// </summary>
        IEmployeesExternal EmployeesExternal { get; }

        /// <summary>
        /// Gets the IRoomsExternal.
        /// </summary>
        IRoomsExternal RoomsExternal { get; }

        /// <summary>
        /// Gets the ISchoolHourEntriesExternal.
        /// </summary>
        ISchoolHourEntriesExternal SchoolHourEntriesExternal { get; }

        /// <summary>
        /// Gets the ISchoolHourEntryStartAndEndTimeExternal.
        /// </summary>
        ISchoolHourEntryStartAndEndTimeExternal SchoolHourEntryStartAndEndTimeExternal { get; }

        /// <summary>
        /// Gets the ISchoolHoursPlansExternal.
        /// </summary>
        ISchoolHoursPlansExternal SchoolHoursPlansExternal { get; }

        /// <param name='body'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<PagedResponseDepartmentsExternalResponse>> PostWithHttpMessagesAsync(ActiveDepartmentsExternalRequest body = default(ActiveDepartmentsExternalRequest), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <param name='body'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<bool?>> Post1WithHttpMessagesAsync(AggregateExistsExternalRequest body = default(AggregateExistsExternalRequest), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <param name='body'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<PagedResponseAreaOfResponsibilityExternalResponse>> Post2WithHttpMessagesAsync(AreasOfResponsibilityExternalRequest body = default(AreasOfResponsibilityExternalRequest), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <param name='body'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<PagedResponseDayCalendarsExternalResponse>> Post3WithHttpMessagesAsync(DayCalendarsExternalRequest body = default(DayCalendarsExternalRequest), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <param name='body'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<PagedResponseDepartmentsExternalResponse>> Post4WithHttpMessagesAsync(DepartmentsExternalRequest body = default(DepartmentsExternalRequest), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <param name='body'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<PagedResponseEmployeeExternalResponse>> Post5WithHttpMessagesAsync(EmployeesExternalRequest body = default(EmployeesExternalRequest), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <param name='body'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<System.Guid?>> Post6WithHttpMessagesAsync(FindSchoolHourEntryExternalRequest body = default(FindSchoolHourEntryExternalRequest), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <param name='body'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<PagedResponseRoomExternalResponse>> Post7WithHttpMessagesAsync(RoomsExternalRequest body = default(RoomsExternalRequest), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <param name='body'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<PagedResponseSchoolHourEntryExternalResponse>> Post8WithHttpMessagesAsync(SchoolHourEntriesExternalRequest body = default(SchoolHourEntriesExternalRequest), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <param name='schoolHourEntryId'>
        /// The school hour entry id to get start and end time for
        /// </param>
        /// <param name='schoolCode'>
        /// The school code for which to get data.
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<SchoolHourEntryStartAndEndTimeExternalDto>> Post9WithHttpMessagesAsync(System.Guid schoolHourEntryId, string schoolCode, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <param name='body'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<PagedResponseSchoolHoursPlanExternalResponse>> Post10WithHttpMessagesAsync(SchoolHoursPlansExternalRequest body = default(SchoolHoursPlansExternalRequest), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

    }
}
