// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Studica.SchoolAdministration.Client
{
    using Models;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for SchoolHoursPlanDetailsExternal.
    /// </summary>
    public static partial class SchoolHoursPlanDetailsExternalExtensions
    {
            /// <summary>
            /// SchoolHoursPlanDetailsExternal_Get
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// Format - uuid.
            /// </param>
            /// <param name='schoolCode'>
            /// The school code for which to get data.
            /// </param>
            public static SchoolHoursPlanDetailsExternalResponse Get(this ISchoolHoursPlanDetailsExternal operations, System.Guid id, string schoolCode)
            {
                return operations.GetAsync(id, schoolCode).GetAwaiter().GetResult();
            }

            /// <summary>
            /// SchoolHoursPlanDetailsExternal_Get
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// Format - uuid.
            /// </param>
            /// <param name='schoolCode'>
            /// The school code for which to get data.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<SchoolHoursPlanDetailsExternalResponse> GetAsync(this ISchoolHoursPlanDetailsExternal operations, System.Guid id, string schoolCode, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetWithHttpMessagesAsync(id, schoolCode, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
