// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Studica.SchoolAdministration.Client
{
    using Models;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for SchoolHourEntryStartAndEndTimeExternal.
    /// </summary>
    public static partial class SchoolHourEntryStartAndEndTimeExternalExtensions
    {
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='schoolHourEntryId'>
            /// The school hour entry id to get start and end time for
            /// </param>
            /// <param name='schoolCode'>
            /// The school code for which to get data.
            /// </param>
            public static SchoolHourEntryStartAndEndTimeExternalDto Get(this ISchoolHourEntryStartAndEndTimeExternal operations, System.Guid schoolHourEntryId, string schoolCode)
            {
                return operations.GetAsync(schoolHourEntryId, schoolCode).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='schoolHourEntryId'>
            /// The school hour entry id to get start and end time for
            /// </param>
            /// <param name='schoolCode'>
            /// The school code for which to get data.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<SchoolHourEntryStartAndEndTimeExternalDto> GetAsync(this ISchoolHourEntryStartAndEndTimeExternal operations, System.Guid schoolHourEntryId, string schoolCode, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetWithHttpMessagesAsync(schoolHourEntryId, schoolCode, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
