// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Studica.Statistics.Client.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// SubmitHandinsExternalCommand
    /// </summary>
    /// <remarks>
    /// Upload data about handins (to be used for statistics about written
    /// absence)
    /// </remarks>
    public partial class SubmitHandinsExternalCommand
    {
        /// <summary>
        /// Initializes a new instance of the SubmitHandinsExternalCommand
        /// class.
        /// </summary>
        public SubmitHandinsExternalCommand()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SubmitHandinsExternalCommand
        /// class.
        /// </summary>
        /// <param name="handins">New handins to create</param>
        /// <param name="schoolCode">String</param>
        public SubmitHandinsExternalCommand(IList<ExternalHandinDto> handins, string schoolCode)
        {
            Handins = handins;
            SchoolCode = schoolCode;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets new handins to create
        /// </summary>
        [JsonProperty(PropertyName = "handins")]
        public IList<ExternalHandinDto> Handins { get; set; }

        /// <summary>
        /// Gets or sets string
        /// </summary>
        /// <remarks>
        /// The school code for which to get data.
        /// </remarks>
        [JsonProperty(PropertyName = "schoolCode")]
        public string SchoolCode { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Handins == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Handins");
            }
            if (SchoolCode == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "SchoolCode");
            }
            if (Handins != null)
            {
                foreach (var element in Handins)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
            if (SchoolCode != null)
            {
                if (SchoolCode.Length > 6)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "SchoolCode", 6);
                }
                if (SchoolCode.Length < 6)
                {
                    throw new ValidationException(ValidationRules.MinLength, "SchoolCode", 6);
                }
            }
        }
    }
}
