// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Studica.Students.Client
{
    using Microsoft.Rest;
    using Models;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// StudentsExternal operations.
    /// </summary>
    public partial interface IStudents
    {
        /// <param name='institutionNumber'>
        /// Institution number where student belongs to.
        /// </param>
        /// <param name='pageNumber'>
        /// </param>
        /// <param name='pageSize'>
        /// </param>
        /// <param name='inlineCount'>
        /// </param>
        /// <param name='studyStartDateFrom'>
        /// </param>
        /// <param name='studyStartDateTo'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="Microsoft.Rest.HttpOperationException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.SerializationException">
        /// Thrown when unable to deserialize the response
        /// </exception>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown when a required parameter is null
        /// </exception>
        Task<HttpOperationResponse<PagedResponse1>> GetWithHttpMessagesAsync(string institutionNumber, int pageNumber, int pageSize, bool inlineCount, System.DateTime studyStartDateFrom, System.DateTime studyStartDateTo, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
    }
}
