// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Studica.SchoolAdministration.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class PagedResponse1EmployeeResponse
    {
        /// <summary>
        /// Initializes a new instance of the PagedResponse1EmployeeResponse
        /// class.
        /// </summary>
        public PagedResponse1EmployeeResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PagedResponse1EmployeeResponse
        /// class.
        /// </summary>
        public PagedResponse1EmployeeResponse(IList<EmployeeResponse> items = default(IList<EmployeeResponse>), int? totalItems = default(int?))
        {
            Items = items;
            TotalItems = totalItems;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "items")]
        public IList<EmployeeResponse> Items { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "totalItems")]
        public int? TotalItems { get; private set; }

    }
}
