// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Studica.Students.Client.Models
{
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Student_Study
    /// </summary>
    public partial class StudentStudy
    {
        /// <summary>
        /// Initializes a new instance of the StudentStudy class.
        /// </summary>
        public StudentStudy()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the StudentStudy class.
        /// </summary>
        /// <param name="id">The id of the study</param>
        /// <param name="departmentId">Id of the department that student is
        /// affiliated to.</param>
        /// <param name="educationId">Id of the education (from UMO) that the
        /// study is linked to</param>
        /// <param name="studyStartDate">Study date of start.</param>
        /// <param name="studentTypes">StudentTypes associated with the
        /// student.</param>
        /// <param name="dsDepartmentNumber">DS Department number that student
        /// is affiliated to.</param>
        /// <param name="educationName">Name of the education from UMO</param>
        /// <param name="coesa">CØSA number of education from UMO</param>
        /// <param name="educationVersion">Education version from UMO</param>
        /// <param name="studyExpectedCompletionDate">Expected completion date
        /// of study.</param>
        /// <param name="studyEndDate">Study end date</param>
        /// <param name="studyEndCauseId">Id of study end cause</param>
        /// <param name="studyEndCauseCode">The UMO code for ending the
        /// study</param>
        /// <param name="studyEndCause">UMO description for cause for study
        /// end.</param>
        /// <param name="studyCancellationCauseCode">The cancellation code for
        /// ending the study. Possible values include: 'StudyNotStarted',
        /// 'Absence', 'Illness', 'EducationalRequirements', 'ChangedStudy',
        /// 'ChangedSchool', 'ChangedSchoolAndChangedStudy', 'Other',
        /// 'Unknown', 'Deceased', 'WrittenAgreementTerminated',
        /// 'CompletedGF2NotContinuing', 'NotPassedFinalExam',
        /// 'AdmissionExamNotPassedAndInterviewDenied',
        /// 'AdmissionExamNotPassedAndDidNotShowAtInterview',
        /// 'AdmissionInterviewNotPassed',
        /// 'AdmissionExamPassedButInterviewDenied',
        /// 'AdmissionExamPassedButDidNotShowAtInterview'</param>
        public StudentStudy(System.Guid id, System.Guid departmentId, System.Guid educationId, System.DateTime studyStartDate, IList<StudyStudentType> studentTypes, string dsDepartmentNumber = default(string), string educationName = default(string), string coesa = default(string), string educationVersion = default(string), System.DateTime? studyExpectedCompletionDate = default(System.DateTime?), System.DateTime? studyEndDate = default(System.DateTime?), System.Guid? studyEndCauseId = default(System.Guid?), string studyEndCauseCode = default(string), string studyEndCause = default(string), string studyCancellationCauseCode = default(string))
        {
            Id = id;
            DepartmentId = departmentId;
            DsDepartmentNumber = dsDepartmentNumber;
            EducationId = educationId;
            EducationName = educationName;
            Coesa = coesa;
            EducationVersion = educationVersion;
            StudyStartDate = studyStartDate;
            StudyExpectedCompletionDate = studyExpectedCompletionDate;
            StudyEndDate = studyEndDate;
            StudyEndCauseId = studyEndCauseId;
            StudyEndCauseCode = studyEndCauseCode;
            StudyEndCause = studyEndCause;
            StudyCancellationCauseCode = studyCancellationCauseCode;
            StudentTypes = studentTypes;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the id of the study
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public System.Guid Id { get; set; }

        /// <summary>
        /// Gets or sets id of the department that student is affiliated to.
        /// </summary>
        [JsonProperty(PropertyName = "departmentId")]
        public System.Guid DepartmentId { get; set; }

        /// <summary>
        /// Gets or sets DS Department number that student is affiliated to.
        /// </summary>
        [JsonProperty(PropertyName = "dsDepartmentNumber")]
        public string DsDepartmentNumber { get; set; }

        /// <summary>
        /// Gets or sets id of the education (from UMO) that the study is
        /// linked to
        /// </summary>
        [JsonProperty(PropertyName = "educationId")]
        public System.Guid EducationId { get; set; }

        /// <summary>
        /// Gets or sets name of the education from UMO
        /// </summary>
        [JsonProperty(PropertyName = "educationName")]
        public string EducationName { get; set; }

        /// <summary>
        /// Gets or sets CØSA number of education from UMO
        /// </summary>
        [JsonProperty(PropertyName = "coesa")]
        public string Coesa { get; set; }

        /// <summary>
        /// Gets or sets education version from UMO
        /// </summary>
        [JsonProperty(PropertyName = "educationVersion")]
        public string EducationVersion { get; set; }

        /// <summary>
        /// Gets or sets study date of start.
        /// </summary>
        [JsonConverter(typeof(DateJsonConverter))]
        [JsonProperty(PropertyName = "studyStartDate")]
        public System.DateTime StudyStartDate { get; set; }

        /// <summary>
        /// Gets or sets expected completion date of study.
        /// </summary>
        [JsonConverter(typeof(DateJsonConverter))]
        [JsonProperty(PropertyName = "studyExpectedCompletionDate")]
        public System.DateTime? StudyExpectedCompletionDate { get; set; }

        /// <summary>
        /// Gets or sets study end date
        /// </summary>
        [JsonConverter(typeof(DateJsonConverter))]
        [JsonProperty(PropertyName = "studyEndDate")]
        public System.DateTime? StudyEndDate { get; set; }

        /// <summary>
        /// Gets or sets id of study end cause
        /// </summary>
        [JsonProperty(PropertyName = "studyEndCauseId")]
        public System.Guid? StudyEndCauseId { get; set; }

        /// <summary>
        /// Gets or sets the UMO code for ending the study
        /// </summary>
        [JsonProperty(PropertyName = "studyEndCauseCode")]
        public string StudyEndCauseCode { get; set; }

        /// <summary>
        /// Gets or sets UMO description for cause for study end.
        /// </summary>
        [JsonProperty(PropertyName = "studyEndCause")]
        public string StudyEndCause { get; set; }

        /// <summary>
        /// Gets or sets the cancellation code for ending the study. Possible
        /// values include: 'StudyNotStarted', 'Absence', 'Illness',
        /// 'EducationalRequirements', 'ChangedStudy', 'ChangedSchool',
        /// 'ChangedSchoolAndChangedStudy', 'Other', 'Unknown', 'Deceased',
        /// 'WrittenAgreementTerminated', 'CompletedGF2NotContinuing',
        /// 'NotPassedFinalExam', 'AdmissionExamNotPassedAndInterviewDenied',
        /// 'AdmissionExamNotPassedAndDidNotShowAtInterview',
        /// 'AdmissionInterviewNotPassed',
        /// 'AdmissionExamPassedButInterviewDenied',
        /// 'AdmissionExamPassedButDidNotShowAtInterview'
        /// </summary>
        [JsonProperty(PropertyName = "studyCancellationCauseCode")]
        public string StudyCancellationCauseCode { get; set; }

        /// <summary>
        /// Gets or sets studentTypes associated with the student.
        /// </summary>
        [JsonProperty(PropertyName = "studentTypes")]
        public IList<StudyStudentType> StudentTypes { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (StudentTypes == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "StudentTypes");
            }
            if (StudentTypes != null)
            {
                foreach (var element in StudentTypes)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
